name: ci-golang-workflow
on:
  pull_request:
    branches:
      - main
jobs:
  test-golang-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Setup go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3
      - name: "Run tests"
        run: go test math
      - name: "Run application"
        run: go run math.go