name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  test-golang-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Setup go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.3

      - name: "Run tests"
        run: go test math

      - name: "Run application"
        run: go run math.go

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: loxt/fullcycle3.0-continuous-integration:latest