name: ci-golang-workflow
on:
  push:
    branches:
      - main
jobs:
  test-golang-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - with:
          go-version: 1.18.3
      - run: go test math.go
      - run: go run math.go